### ISSUE TITLE
Firework schematic recipe messes with recipe for creeper head banner pattern

### ISSUE THREAD

**Issue by thelegitdolt** [CreativityShark/pyrotasticv2#4]
<img width="273" alt="Screen Shot 2022-09-29 at 2 06 33 AM" src="https://user-images.githubusercontent.com/50085439/192990653-2d2d1016-0f01-4df1-bbc3-7367bdb54a22.png">
<img width="616" alt="Screen Shot 2022-09-29 at 2 08 09 AM" src="https://user-images.githubusercontent.com/50085439/192990832-ecdf3e21-713f-47f6-b82f-c3d70fd7a452.png">

**Comment by thelegitdolt** [comment]
<img width="597" alt="Screen Shot 2022-09-29 at 2 10 00 AM" src="https://user-images.githubusercontent.com/50085439/192991174-44899375-b6ce-4947-bdee-95fab0708f02.png">
also this one

**Comment by CreativityShark** [comment]
Changed the schematic recipe by swapping out mob heads as an ingredient for Creeper Banner Patterns. It isn't perfect, but it's functional.
